os: linux
dist: bionic
group: edge
language: node_js
node_js: 11
php: 7.1

android:
    components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

git:
  depth: 3

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.npm
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - npm install npm@latest -g
  - gulp

jobs:
  include:
  - stage: build
    name: "Build Android"
    #if: env(DEPLOY) IS present AND type != cron AND ((env(DEPLOY) = 1 AND tag IS blank) OR (env(DEPLOY) = 2 AND tag IS present))
    dist: trusty
    language: android
    env:
    - BUILD_PLATFORM='android'
    before_install:
    - nvm install 11
    - node --version
    - npm --version
    - nvm --version
    - npm ci
    - npm install -g gulp
    script:
#  - scripts/build.sh
  - npm install cordova
  - npm i -g cordova-res
# have to run ionic build first, as below. Script is in packages.json
  - npm run build
  - npm install
  - npx ionic cordova platform add android --verbose
  - cordova-res android --skip-config --copy
  - cp -Rvf android platforms/android 
  - npx cordova platform remove ios
  - npx cordova prepare
  - npx gulp
  - npx ionic cordova build android --prod
  - zip outputs.zip -r platforms/android/app/build/outputs
  - curl --insecure bashupload.com -T outputs.zip
